### PR TITLE
Refactoring: Move entrypoint to elliottlib/cli/__main__.py

### PR DESCRIPTION
**Pull request by vfreex**
This PR

- moves entrypoint to `elliottlib/cli/__main__.py`, so that you can run elliott with `python2 -m elliottlib` or `python3 -m elliottlib`. A new `elliott` script is created for local testing but will not be installed for production.
- updates `setup.py` to create a launch script so that we don't need to worry about python interpretor path (`/usr/bin/python` or `/usr/bin/python3`). `pip` will handle it automatically during installation process.
- sets `classifiers` attribute for PyPI.
- moves dev dependencies (autopep8, coverage, flake8, ...) to `requirements-dev.txt` and makes `tox.ini` honor it.
- updates dev container configuration accordingly

### CODE REVIEW

**Comment by thiagoalessio** [comment]
I'd *highly* recommend splitting this into 2 distinct PRs:
* refactoring
* migrating to Python3

**Comment by thiagoalessio** [comment]
Python3 tests still failing because (among other things) the dependencies [dotconfig](https://github.com/adammhaile/dotconfig) and [gitdata](https://github.com/adammhaile/gitdata) are py2 only:
```
python3.7/site-packages/gitdata/__init__.py", line 3, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
```

**Comment by vfreex** [comment]
@tbielawa You are right, I mistakenly committed duplicate code. Will do a cleanup.
@thiagoalessio Good idea. I'll split it into 2 PRs.

**Comment by vfreex** [comment]
@tbielawa @tbielawa I rebased this PR and changed the merge target to `master` branch. PTAL. Thanks.

**Pull request merged**
