### PR TITLE
[ART-1312] Drop Python2 support

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by vfreex** [comment]
Would also like to remove Python 2.7 info from setup.py. otherwise LGTM.

**Comment by thiagoalessio** [comment]
@vfreex setup.py done :heavy_check_mark:

**Comment by tbielawa** [comment]
Would you mind removing the `elliott` part of our tox command too? It will stop this warning from happening (we never `import elliott` anywhere, it's always `elliottlib` now):

> Coverage.py warning: Module elliott was never imported. (module-not-imported)

In tox.ini:

```diff
diff --git a/tox.ini b/tox.ini
index 35b59ed..f92174d 100644
--- a/tox.ini
+++ b/tox.ini
@@ -9,7 +9,7 @@ setenv =
     PYTHONDONTWRITEBYTECODE=1
 commands =
     flake8
-    coverage run --branch --source elliott,elliottlib -m unittest discover -t . -s tests/
+    coverage run --branch --source elliottlib -m unittest discover -t . -s tests/
     coverage report
 
 [flake8]
```

**Comment by thiagoalessio** [comment]
@tbielawa done :heavy_check_mark:

**Comment by tbielawa** [comment]
We have confirmation from Luke that we're OK to drop py2 support.

**Pull request merged**
