### PR TITLE
Python 3 porting: Run `futurize --stage1`

### PR DESCRIPTION
**Pull request by vfreex**
I am trying [Futurize][] for porting Python 2 code to Python 3.
The tool is one of recommended tools listed on the official Python HOWTOs documentation [Porting Python 2 Code to Python 3][].

Futurize can divide the porting into two stages. Stage 1 is for “safe” changes that modernize the code but do not break Python 2.6 compatibility or introduce a depdendency on the future package. Stage 2 is to complete the process.

The PR is generated with the following command:

```bash
futurize --stage1 --unicode-literals --nobackups --write .
```

[Porting Python 2 Code to Python 3]: https://docs.python.org/3/howto/pyporting.html
[Futurize]: http://python-future.org/automatic_conversion.html

## NOTE
Only stage 1 of the Futurize porting process is run so that we are expecting this will not break our existing Python 2 compatibility but it will still not run on Python 3.

### CODE REVIEW

**Comment by yazug** [comment]
I would recommend fixing up the print() commands first by itself, there a couple of str/unicode vs string ... issues that the unittests caught six.string_types could help or some python version guards.

**Comment by sosiouxme** [comment]
@vfreex Your python expertise exceeds mine and these seem like innocuous enough changes. Would like at least a quick look from the other pythonistas but I'm also OK with merging this at end of sprint if they haven't. Do you want to get this in first or should this be closed in favor of https://github.com/openshift/elliott/pull/85?

**Comment by vfreex** [comment]
@sosiouxme Thank you. That is a high compliment! Although I don't think I have mastered the "Python way" or any advanced features to implement things and consistently introduce "Java style" into a Python program.

Yes, would like to have other guys take a look as well, but it seems to me that this kind of PRs always gets deprioritized and people are afraid of breaking things.

I would like to merge this kind of changes on Friday or Monday to avoid the building and promoting days. (We can always rollback if something is broken)

**Comment by vfreex** [comment]
@sosiouxme @thiagoalessio Regarding the build failure, I looked at the Jenkins log and found the following log:
```
    Executing gcov (find /mnt/workspace/jenkins/working/art-tools_elliott_PR-82 -not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**' -type f -name '*.gcno'  -exec gcov -pb  {} +)
[90m==>[0m Collecting reports
    Generating coverage xml reports for Python
    [32m+[0m /mnt/workspace/jenkins/working/art-tools_elliott_PR-82/coverage.xml bytes=139272
[90m==>[0m Uploading
    .url https://codecov.io
    .query commit=3012d9adaa3b7cc3dfbfad222e9647a8939bb5f3&branch=PR-82&pr=82&build_url=https%3A%2F%2Fsaml.buildvm.openshift.eng.bos.redhat.com%3A8888%2Fjob%2Fart-tools%2Fjob%2Felliott%2Fjob%2FPR-82%2F1%2F&token=<secret>&service=jenkins&build=1&package=py2.0.15
    Pinging Codecov...
[41mError:[0m[91m HTTPSConnectionPool(host='codecov.io', port=443): Max retries exceeded with url: /upload/v4?commit=3012d9adaa3b7cc3dfbfad222e9647a8939bb5f3&branch=PR-82&pr=82&build_url=https%3A%2F%2Fsaml.buildvm.openshift.eng.bos.redhat.com%3A8888%2Fjob%2Fart-tools%2Fjob%2Felliott%2Fjob%2FPR-82%2F1%2F&token=****&service=jenkins&build=1&package=py2.0.15 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f82bccb9c50>: Failed to establish a new connection: [Errno 110] Connection timed out',))[0m

[42mTip:[0m[32m See all example repositories: https://github.com/codecov?query=example[0m
[92mSupport channels:[0m
  Email:   hello@codecov.io
  IRC:     #codecov
  Gitter:  https://gitter.im/codecov/support
  Twitter: @codecov
```
It seems to me that codecov was attempted to uploading something to a public server, but it was rejected by firewall rules on BuildVM.

**Pull request merged**
