### PR TITLE
Fix bug categorization issue with sub_components

### PR DESCRIPTION
**Pull request by vfreex**
`sub_components` field is not in the bug query so `bug.sub_component` field is absent.

### CODE REVIEW

**Comment by joepvd** [comment]
Nice find! Think it would not hurt to have that attribute also added to `def blocker_search`

**Comment by sosiouxme** [comment]
/approve
fix the tests tho :-P

**Review by thiagoalessio — APPROVED** [review]
/lgtm

**Comment by Ximinhan** [comment]
rebased in https://github.com/openshift/elliott/pull/337, close this for now

**Pull request closed without merging**
