### PR TITLE
python 3 - compatiblity fixes

### PR DESCRIPTION
**Pull request by yazug**
split out a couple of other patches and have a long patch set of different python 2 vs 3 fixes/changes
tox -e py3 now works and passes locally

Most of these should be py2 backward compatible but some changes may impact runtime usage of the tool, more testing is required before anything can be said about whether it works or not.

Related: issue #84

### CODE REVIEW

**Comment by vfreex** [comment]
Thank you for helping with this. Yes we are currently in the progress of Python 3 migration. I will do a review in a few days.

**Comment by vfreex** [comment]
Hi @yazug, could you do a rebase on top of `python-3` branch?

**Comment by yazug** [comment]
> Hi @yazug, could you do a rebase on top of `python-3` branch?

done, updated and fixed up a couple of new instances of keys()/items() as lists issues

**Comment by vfreex** [comment]
After looking at the PR, I think it is safe to merge. What this does are basically:

1. replaces old APIs with new ones:
    - `iteritems` to `items` for `dict`s.
    - explicitly converts the return value of `dict.keys()` and `dict.values()` to `list`.
    - import wrapper functions with `future.standard_library.install_aliases`
2. consolidate string types using `builtins.str`

I would like to give a LGTM. @thiagoalessio @sosiouxme @shiywang Please also take a look. I plan to merge it if we get another LGTM.

/lgtm

**Pull request merged**
